repos:
  - repo: local
    hooks:
      - id: ruff
        name: Ruff
        entry: uv run ruff check --fix
        language: system
        types: [python]
      - id: ruff-format
        name: Ruff Format
        entry: uv run ruff format
        language: system
        types: [python]
